# Kitty Keybinds

# Scrolling Keys
map ctrl+shift+i      scroll_line_up
map ctrl+shift+u      scroll_line_down
map ctrl+shift+p      scroll_page_up
map ctrl+shift+o      scroll_page_down

# Tab Keys
map ctrl+.            next_tab
map ctrl+,            previous_tab
map ctrl+shift+enter  new_tab

map ctrl+space        set_tab_title " "

# Window Keys
map ctrl+enter        new_window
map ctrl+j            next_window
map ctrl+k            previous_window
map ctrl+f            first_window

map ctrl+a            move_window_to_top
map ctrl+shift+j      move_window_forward
map ctrl+shift+k      move_window_backward
