local mason_lspconfig = require "mason-lspconfig"
mason_lspconfig.setup {
  ensure_installed = {
    "lua_ls",
    "bashls",
    "clangd",
    "cssls",
    "debugpy",
    "eslint",
    "eslint_d",
    "glow",
    "html",
    "jedi_language_server",
    "lemminx",
    "luacheck",
    "markdown_oxide",
    "mardownlint",
    "marksman",
    "prettier",
    "pylint",
    "pyright",
    "pylsp",
    "stylua",
    "tsserver",
    "typos_lsp",
    "csharp_ls",
    "rust_analyzer",
  },
  automatic_installation = true,
}
