print(bold() .. [[                .                 ]])
print(bold() .. [[          ..  ..' .  ...  ..      ]])
print(bold() .. [[       ,,:okc;xlcok;:kkkc;kx:..   ]])
print(bold() .. [[     ;kkkkkkkkkkkdoookdoxxodk.    ]])
print(bold() .. [[    ;dkddkxoxkdooxxxxkkxkkxxk:.   ]])
print(bold() .. [[  .;cdkxxkxdddoooxkxddxkkkkkkl:'. ]])
print(bold() .. [[  .;olloddoxlcclodxllodxxdxddxd,  ]])
print(bold() .. [[  ..       l,;,:llo::xo;;,;' ';,  ]])
print(bold() .. [[              .;looc:'.           ]])
print(bold() .. [[ .            ::;::,'            .]])
print(bold() .. [[ :;,        ';';:;c,.          ...]])
print(bold() .. [[.;do..    .lcx::l:cc''..     ..,. ]])
print(bold() .. [[.cdo:cc..:,l:llc:';oxxo;.....,;;' ]])
print(bold() .. [['cxkkkkkkkdlc:      ;cokkkkkkd::, ]])
print(bold() .. [[  ','.,okko:.        ;lkkkkdl;;.  ]])
print(bold() .. [[    ...;lkdo' ,;;.   ldkoll...'   ]])
print(bold() .. [[    ..;cclloccxkkdl,;ookoc;.  .   ]])
print(bold() .. [[     ,ddo:c:oddddxkc;:okxd .c     ]])
print(bold() .. [[  ..   'ck:   ..:ckc:kkk,'::c.;   ]])
print(bold() .. [[  ,:l;,:d.'lll  ':k.,..:co.. ..   ]])
print(bold() .. [[  .;k;.lxl;c,,..lc:.,...;:,'.''   ]])
print(bold() .. [[  ..llo:lkl:..',c::.'c,'.'''...   ]])
print(bold() .. [[    .;xc:xxkkx:' :k;;k;           ]])
print(bold() .. [[       ';odkkkkkkkd    lddoc.     ]])
print(bold() .. [[         cccool....;:::''...      ]])
print(bold() .. [[         ...',.    ....           ]])
print(reset())
