#! /bin/sh

POLYBAR_CONFIG="$HOME/.config/bspwm/config.ini"

picom --experimental-backends -cb &

nitrogen --restore &
polybar -c "$POLYBAR_CONFIG" left &
polybar -c "$POLYBAR_CONFIG" left-music &
polybar -c "$POLYBAR_CONFIG" center &
polybar -c "$POLYBAR_CONFIG" right-search &
polybar -c "$POLYBAR_CONFIG" right-mem &
polybar -c "$POLYBAR_CONFIG" right-cpu &
polybar -c "$POLYBAR_CONFIG" right-sys &
polybar -c "$POLYBAR_CONFIG" right-bat &
polybar -c "$POLYBAR_CONFIG" right-power &
nm-applet &
pa-applet &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width            3
bspc config normal_border_color     "#303030"
bspc config focused_border_color    "#ff0000"
bspc config window_gap              10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
